name: 'Squidler Check Action'
description: 'Performs a Squidler check on your project'
author: 'Squidler'
inputs:
  token:
    description: 'Squidler API token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'blue'
